## ===============================
## = Hibernate datasource
## ===============================
#  spring:
#  datasource:
#  url: jdbc:mysql://localhost:3306/electronics
#  username: root
#  password: root
#  tomcat:
#  test-while-idle: true
#  validation-query: SELECT 1
## ===============================
## = JPA configurations
## ===============================
#  jpa:
#    showProduct-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
## ===============================
## = MAIL configurations
## ===============================
#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    username: email1sender12@gmail.com
#    password: Emailemail
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    protocol: smtp
#    test-connection: false
## ===============================
## = LOGGING configurations
## ===============================